### ISSUE TITLE
ステージ作成

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#1]
だいたい10個くらい

**Comment by kyamada101** [comment]
7/17　ステージ1～10の案
![ステージ1](https://user-images.githubusercontent.com/45187627/61445438-5ea48f00-a988-11e9-9c82-a49d92a047bf.png)
![ステージ2](https://user-images.githubusercontent.com/45187627/61445439-5f3d2580-a988-11e9-936e-fed741bf1611.png)
![ステージ3](https://user-images.githubusercontent.com/45187627/61445440-5f3d2580-a988-11e9-90bd-244349c40b7e.png)
![新ステージ4](https://user-images.githubusercontent.com/45187627/62104358-53335b00-b2da-11e9-82ba-e6f042eda439.png)
![ステージ5](https://user-images.githubusercontent.com/45187627/62104364-59293c00-b2da-11e9-973e-712f3d1f0ff4.jpg)
![ステージ6](https://user-images.githubusercontent.com/45187627/62104370-5f1f1d00-b2da-11e9-8543-c4a3613f5d54.jpg)
![新ステージ7](https://user-images.githubusercontent.com/45187627/62190298-fc965180-b3ab-11e9-822e-ab38ddcc34b3.png)
![ステージ8](https://user-images.githubusercontent.com/45187627/62190305-028c3280-b3ac-11e9-8a3a-3f83bbbfa23e.jpg)
![ステージ9](https://user-images.githubusercontent.com/45187627/62192569-d1623100-b3b0-11e9-9e45-25ba7d75202e.png)
![ステージ10](https://user-images.githubusercontent.com/45187627/62102739-fe411600-b2d4-11e9-9bea-2208e2ea0bcd.jpg)

**Comment by SaeIchinose** [comment]
ステージ1~7の詳細案
[unilab2019_stage1.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409775/unilab2019_stage1.xlsx)
[unilab2019_stage2.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409776/unilab2019_stage2.xlsx)
[unilab2019_stage3.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409777/unilab2019_stage3.xlsx)
[unilab2019_stage4.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409778/unilab2019_stage4.xlsx)
[unilab2019_stage5.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409780/unilab2019_stage5.xlsx)
[unilab2019_stage6.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409781/unilab2019_stage6.xlsx)
[unilab2019_stage7.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409782/unilab2019_stage7.xlsx)

**Comment by SaeIchinose** [comment]
あと追加でいくつか作ってみたんであげときます
[unilab2019_stage（敵と1upのチュートリアル）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409789/unilab2019_stage.1up.xlsx)
[unilab2019_stage（ドアワープチュートリアル）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409790/unilab2019_stage.xlsx)
[unilab2019_stage（ドアワープ＆敵）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409791/unilab2019_stage.xlsx)
[unilab2019_stage（ワープ迷路）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3409792/unilab2019_stage.xlsx)

**Comment by kyamada101** [comment]
ステージの規格サイズ(jsonファイルのwidth×height)
width:24
height:18

**Comment by kyamada101** [comment]
7/30
・元々のステージ7だったやつが難しすぎるだろうという話になったのでステージ10に変更しました。これからまた変わるかもしれません
・ステージ4を1UP・敵・コインのシステムのチュートリアルに変更
このためステージ4⇒5、5⇒6、6⇒7になりました。上のスケッチは変更済みのものに変えてあります

**Comment by SaeIchinose** [comment]
新しいstage4の詳細案
[unilab2019_stage4改.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3450029/unilab2019_stage4.xlsx)
手書き案とは少し異なります。

**Comment by kyamada101** [comment]
7/31
ドアチュートリアルとしてステージ7を追加、昨日のステージ7を8に変更
ステージ9を追加
