### ISSUE TITLE
画面遷移

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#22]
ステージ選択画面からボタン押したら各ステージ画面に遷移できるようにしたい
参考サイト：
http://punyo-er-met.hateblo.jp/entry/2016/04/10/103632

**Comment by kyamada101** [comment]
![画面遷移](https://user-images.githubusercontent.com/45187627/62105225-b920e200-b2dc-11e9-9c39-d03e82d84338.png)
画面遷移のアクティビティ図っぽいもの
