### ISSUE TITLE
基盤作成

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#4]
内部構造やっときます

**Comment by SaeIchinose** [comment]
ステージクリア時のスコア制度（ゴールした時のみ計算）
・実行コードの行数が少ないとスコアアップ
・実行タイムステップ数が少ないほどスコアアップ(歩数制限はなし)
・コインを取るとスコアアップ
（コード, タイムステップのスコアとトレードオフになってしまうため、コイン1つ＝コード5行分＝タイムステップ10ステップ分等の配分が良い?）

スコア計算式例（係数は変わる可能性あり）(合計100前後になるように調整)
スコア=80(基本点)+(コインの枚数)+(残機数)＋（（コード数）ー(標準コード行数)）＋(（タイムステップ数)ー（標準タイムステップ数）） 
or
スコア=80(基本点)+(コインの枚数)＋（（コード数）ー(標準コード行数)）＋(（タイムステップ数)ー（標準タイムステップ数））
