### ISSUE TITLE
Formボタン配置

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#5]
単純に画面レイアウトだけ作って欲しい。GUIでポチポチやればできる。
押しても何も起きない状態でいい

**Comment by sirokome19** [comment]
TableLayoutPanelを使えば勝手にレスポンシブデザインになるみたい。
ソースは以下
https://teratail.com/questions/58826

**Comment by SaeIchinose** [comment]
コマンド一覧（**太字**は去年と異なるところ）

前に進む
左を向く
右を向く
**止まる**

if文
もし**{前，後ろ，右，左}**に**{壁，敵，ドア}**があったら
（去年は｛前に壁があったら，右に壁があったら，...｝で選択肢が異常に多かったから、場所と物体で選択肢を別にできると嬉しい）

for文
{n}回繰り返す

while文
ずっと

実行
全部消す
**選択した部分を消す**
プレイヤーリセット

**Comment by kyamada101** [comment]
小学生がわかるように漢字を変更
「壁」⇒「木」
「敵」⇒「てき」
「繰り返し」⇒「くり返し」
「選択」⇒「せんたく」
「削除」⇒「消す」

GameForm.csの中にも対応箇所がある（Ifbuttunclickとか）ので、そちらの変更もお願いします
