### ISSUE TITLE
敵作成

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#6]

**Comment by SaeIchinose** [comment]
敵が出現するステージの詳細案

[unilab2019_stage4.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440927/unilab2019_stage4.xlsx)
[unilab2019_stage5.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440928/unilab2019_stage5.xlsx)
[unilab2019_stage6.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440929/unilab2019_stage6.xlsx)
[unilab2019_stage7.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440930/unilab2019_stage7.xlsx)
[unilab2019_stage（敵と1upのチュートリアル）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440931/unilab2019_stage.1up.xlsx)
[unilab2019_stage（ドアワープ＆敵）.xlsx](https://github.com/inouelab-waseda/unilab2019/files/3440934/unilab2019_stage.xlsx)

**Comment by SaeIchinose** [comment]
敵の詳細
プレイヤーが敵に当たったら一撃死
ただし、1upアイテムを1つ消費して耐えることができる
余った1upアイテムは次のステージに持ち越せる

**Comment by SaeIchinose** [comment]
**変更，1upはステージごとに清算**
敵との当たり判定は1タイムステップごとに判定を行い、同じマスに敵とプレイヤーが存在したら1機消滅（すれ違いはセーフ）
