### ISSUE TITLE
デバック

### ISSUE THREAD

**Issue by TsuchiyaYosuke** [inouelab-waseda/unilab2019#71]
・実装されていない
//onedelete_Btn（安藤）(済)

**Comment by TsuchiyaYosuke** [comment]
・動いている敵の当たり判定が通らない時がある

**Comment by TsuchiyaYosuke** [comment]
・動いている敵の当たり判定が表示されない（安田）

**Comment by TsuchiyaYosuke** [comment]
・ステージ選択画面の拡大表示対応できていない(内藤)
・スコアボードの表示されていない(土屋)

**Comment by SaeIchinose** [comment]
・リセットしても歩数リセットされない
・アイテム取得してもアイテム消えない
