### ISSUE TITLE
画面作成

### ISSUE THREAD

**Issue by sirokome19** [inouelab-waseda/unilab2019#8]
仮置きの画面それぞれに画面遷移だけできるように(ステージ配置含め)

**Comment by kyamada101** [comment]
7/17作成　ステージの共通フレーム？
![unilabステージ画面原案　7-17](https://user-images.githubusercontent.com/45187627/61445397-4a609200-a988-11e9-9248-f7b1661a69ba.png)

**Comment by sirokome19** [comment]
回復、ここまでは不要。ほかは去年準拠＋ステージ選択。

**Comment by kyamada101** [comment]
![ステージクリア時に表示する別ウィンドウ](https://user-images.githubusercontent.com/45187627/62103264-dc489300-b2d6-11e9-8b0e-482ba97ef187.png)
ステージクリアすると表示する別ウィンドウ
「ステージ選択に戻る」ボタンを押すとステージ選択画面に戻る

**Comment by kyamada101** [comment]
![ステージ選択画面の案](https://user-images.githubusercontent.com/45187627/62103297-ff734280-b2d6-11e9-8375-0952cb9c535e.png)
ステージ選択画面の案
・「ホーム画面に戻る」ボタンはない。
・アプリを消さない限りはスコアを保持。アプリを消すとすべてリセット。
・各ステージはやり直し可能で、前回のスコアを上回った時だけスコアを更新。
・全てのステージをクリアすると（スコアは何点でもいいから）、右上の「合計スコア」表示の上に「All Crear!!」と表示してくれると嬉しい

**Comment by kyamada101** [comment]
![ホーム画面の案](https://user-images.githubusercontent.com/45187627/62103675-0f3f5680-b2d8-11e9-9f69-665cc862e08f.png)
ホーム画面の案。
デザインはおまかせで、下部に「ステージ選択へ」のボタン一つあればいい

**Comment by kyamada101** [comment]
7/31　各ステージ画面の修正案
![各ステージ画面の修正案](https://user-images.githubusercontent.com/45187627/62191583-b7275380-b3ae-11e9-9f1a-7a2263720892.png)
